#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "😵 봄이 사람으로 태어난다면.. 어쩌면 그 사람은 바로 르미가 아닐까? 🤲"

echo "🧐 progress linting check.... 🧐"
npm run lint
echo "🧞‍♀️ lint checking pass 🧞‍♀️"

echo "🧐 progress test check.... 🧐"
npm run test:all
echo "🧞‍♀️ test checking pass 🧞‍♀️"

echo "르미야 시간 나면 치과에서 알바해 너만 보면 입이 안 다물어지니까"